### ISSUE TITLE
注意下代码格式

### ISSUE THREAD

**Issue by hurley25** [xiyou-linuxer/file-monitor_deepin#2]
也可以工具格式化
```shell
indent -bad -bli 0 -ce -kr -nsob -l 150 xx.cpp
```

**Comment by condy0919** [comment]
这工具已经过时了，推荐使用 clang-format, 然后在项目里放置一个大家都遵守的 .clang-format 规范

**Comment by condy0919** [comment]
顺便安利下宋教授的 https://github.com/maskray/ccls

**Comment by hurley25** [comment]
哎，啥过时不过时的，能满足需求，随便一台机器都有的东西才是好用的东西，脚本就不用做那么多适配性的工作。
